// Expo config plugin: fix the `fmt` consteval build error on Xcode 16.3+.
//
// React Native 0.76 vendors an older `fmt` whose `FMT_STRING`/consteval path is
// rejected by the newer Apple Clang shipped with Xcode 16.3+, failing the pod
// build with:
//   "call to consteval function 'fmt::basic_format_string<...>' is not a
//    constant expression"  (ios/Pods/fmt/include/fmt/format-inl.h)
//
// fmt headers are included by many pods (glog, RCT-Folly, React-Core…), so the
// fix must reach every target: we define FMT_USE_CONSTEVAL=0 project-wide in the
// Podfile's post_install, which makes fmt fall back to constexpr and compiles.
//
// Injected idempotently into the existing post_install block generated by Expo.

const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "FMT_USE_CONSTEVAL=0";
const SNIPPET = `
    # --- fmt consteval fix for Xcode 16.3+ (RN 0.76); added by withFmtConstevalFix ---
    installer.pods_project.targets.each do |fmt_fix_target|
      fmt_fix_target.build_configurations.each do |fmt_fix_config|
        fmt_fix_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        fmt_fix_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEVAL=0'
      end
    end
    # --- end fmt consteval fix ---
`;

module.exports = function withFmtConstevalFix(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfile, "utf8");
      if (!contents.includes(MARKER)) {
        // insert right after the post_install block opens
        contents = contents.replace(
          /post_install do \|installer\|\n/,
          (match) => match + SNIPPET + "\n"
        );
        fs.writeFileSync(podfile, contents);
      }
      return cfg;
    },
  ]);
};
